### ISSUE TITLE
Dear gerkovink me trying excute excute.R but me getting error   Error in run.conventional(amp, ms = ms) : object 'ms' not found

### ISSUE THREAD

**Issue by lavanya111** [gerkovink/parlMICE#1]

**Comment by RianneSchouten** [comment]
Dear Lavanya111

Thank you very much for this bug report. In fact, the error was simply due to some information about ms being missing from the Execute.R file. I am sorry! 
I have now changed Execute.R such that it makes sense which ms I use for which simulations. 

For your information: the object 'ms' is the total number of multiply imputed datasets m that I wish to generate. The parlMICE function divides these ms over 1, 2 or 3 cores, giving each core the task to generate m = ms / 2 (or 3) multiply imputed datasets. 

Furthermore, please be aware that the defaults of ampute have now changed. The current version of ampute as it is in package mice, generates a MARRIGHT missingness mechanism. At the time of running the simulations for parlMICE, the defaults of ampute would generate MCAR missingness. Running the same code will therefore not generate the same output!

Please let me know if you have any other questions. 

Kind regards,

Rianne Schouten
